### ISSUE TITLE
sorry，I have some question。

### ISSUE THREAD

**Issue by Damonvvong** [linkedin/swift-style-guide#20]
Could you tell me the reason for "never use the += or + operator to append/concatenate to arrays"?

**Comment by plivesey** [comment]
Compile times. Swift really struggles when you use `+` with complex expressions.

See https://stackoverflow.com/questions/39490808/how-to-merge-multiple-arrays-without-slowing-the-compiler-down (and a bunch of other articles if you google it).

Easier to solve this through style instead of measuring the type checking every time you add a line of code.

**Comment by Damonvvong** [comment]
emmm, I try to find the different from `+` and `append`。
But, I forget the Compile times cost.
Thank you, I will close this issue.

**Comment by drumnkyle** [comment]
We actually should revisit this, because in more recent versions of Swift we found the compilation times were actually now better for the + operator than append and string interpolation. @cezarywojcik: we should look into it more and possibly change this rule. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
